# Generated by Django 5.0.3 on 2024-03-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('rate_cpm', models.CharField(max_length=20)),
                ('rate_per', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=25)),
            ],
        ),
    ]
